/**
 * TRADUÇÃO DOS RAMOS DE ATIVIDADE
 *
 * O mapa de relações (`MAPA_SEGMENTOS_CLIENTES`) fica SÓ em português,
 * de propósito. Ele guarda quem contrata quem — uma marmoraria vende
 * para construtora — e isso não muda com o idioma. Manter três cópias
 * do mapa significaria manter a mesma relação em três lugares, e elas
 * divergiriam na primeira alteração.
 *
 * Aqui mora apenas o dicionário de termos. O fluxo é:
 *
 *   entrada em qualquer idioma  →  canonizarSegmento()  →  termo PT
 *   termo PT  →  MAPA  →  ramos-cliente em PT
 *   ramos-cliente em PT  →  traduzirSegmento()  →  idioma da interface
 *
 * Sem isso, um assinante em Austin que digitava "stonemason" não casava
 * com nada: o produto encontrava as empresas pelo OpenStreetMap, mas a
 * mensagem de abordagem perdia a linha que explica POR QUE aquela
 * empresa foi procurada — justamente a que diferencia o contato.
 */

/** Termo em português → [inglês, espanhol] */
export const TRADUCAO_SEGMENTOS: Record<string, readonly [string, string]> = {
  "Academia": ["Gym", "Gimnasio"],
  "Administradora de condomínios": ["Property management company", "Administradora de condominios"],
  "Administradora de imóveis": ["Real estate management company", "Administradora de inmuebles"],
  "Advocacia": ["Law firm", "Abogacía"],
  "Agenciamento de cargas": ["Freight forwarding", "Agenciamiento de cargas"],
  "Agroindústria": ["Agribusiness", "Agroindustria"],
  "Agência de marketing": ["Marketing agency", "Agencia de marketing"],
  "Agência de viagens": ["Travel agency", "Agencia de viajes"],
  "Alimentícia": ["Food industry", "Industria alimentaria"],
  "Aluguel de caminhões": ["Truck rental", "Alquiler de camiones"],
  "Andaimes e acesso": ["Scaffolding and access", "Andamios y acceso"],
  "Aplicativo de transporte": ["Ride-hailing app", "Aplicación de transporte"],
  "Armazém geral": ["General warehouse", "Almacén general"],
  "Arquitetura": ["Architecture", "Arquitectura"],
  "Arquitetura e design de interiores": ["Architecture and interior design", "Arquitectura y diseño de interiores"],
  "Asilo e casa de repouso": ["Nursing home", "Residencia de ancianos"],
  "Automação residencial": ["Home automation", "Automatización residencial"],
  "Autopeças": ["Auto parts", "Autopartes"],
  "Avicultura": ["Poultry farming", "Avicultura"],
  "Açougue": ["Butcher shop", "Carnicería"],
  "Banco": ["Bank", "Banco"],
  "Bar": ["Bar", "Bar"],
  "Brinquedos": ["Toys", "Juguetes"],
  "Buffet de eventos": ["Event catering", "Catering para eventos"],
  "Buffet e eventos": ["Catering and events", "Catering y eventos"],
  "Cafeteria": ["Coffee shop", "Cafetería"],
  "Caldeiraria": ["Boilermaking", "Calderería"],
  "Call center": ["Call center", "Call center"],
  "Cartório": ["Notary office", "Notaría"],
  "Casa de festas": ["Event venue", "Salón de fiestas"],
  "Casa de shows": ["Concert venue", "Sala de conciertos"],
  "Cerealista": ["Grain trader", "Cerealista"],
  "Cerâmica": ["Ceramics", "Cerámica"],
  "Clube esportivo": ["Sports club", "Club deportivo"],
  "Clínica": ["Clinic", "Clínica"],
  "Clínica de estética": ["Aesthetic clinic", "Clínica estética"],
  "Clínica de fisioterapia": ["Physiotherapy clinic", "Clínica de fisioterapia"],
  "Clínica médica": ["Medical clinic", "Clínica médica"],
  "Clínica odontológica": ["Dental clinic", "Clínica dental"],
  "Clínica oftalmológica": ["Eye clinic", "Clínica oftalmológica"],
  "Clínica veterinária": ["Veterinary clinic", "Clínica veterinaria"],
  "Comunicação visual": ["Signage and visual communication", "Comunicación visual"],
  "Comércio": ["Retail and trade", "Comercio"],
  "Comércio de materiais": ["Building materials trade", "Comercio de materiales"],
  "Comércio exterior": ["Foreign trade", "Comercio exterior"],
  "Concessionária": ["Car dealership", "Concesionaria"],
  "Condomínio comercial": ["Commercial building", "Condominio comercial"],
  "Condomínio de alto padrão": ["Luxury residential complex", "Condominio de alto nivel"],
  "Condomínio residencial": ["Residential building", "Condominio residencial"],
  "Confecção": ["Clothing manufacturer", "Confección"],
  "Confinamento de gado": ["Cattle feedlot", "Engorde de ganado"],
  "Conservação e zeladoria": ["Facility upkeep", "Conservación y mantenimiento"],
  "Construtora": ["Construction company", "Constructora"],
  "Construção civil": ["Civil construction", "Construcción civil"],
  "Construção civil pesada": ["Heavy civil construction", "Construcción civil pesada"],
  "Consultoria agronômica": ["Agronomic consulting", "Consultoría agronómica"],
  "Contabilidade": ["Accounting", "Contabilidad"],
  "Cooperativa agrícola": ["Agricultural cooperative", "Cooperativa agrícola"],
  "Corretor de imóveis": ["Real estate broker", "Agente inmobiliario"],
  "Cosméticos": ["Cosmetics", "Cosméticos"],
  "Coworking": ["Coworking", "Coworking"],
  "Creche": ["Daycare", "Guardería"],
  "Curso preparatório": ["Test prep school", "Curso preparatorio"],
  "Data center": ["Data center", "Centro de datos"],
  "Dedetização e controle de pragas": ["Pest control", "Fumigación y control de plagas"],
  "Demolição": ["Demolition", "Demolición"],
  "Dentista": ["Dentist", "Dentista"],
  "Depósito": ["Warehouse", "Depósito"],
  "Desentupimento": ["Drain unclogging", "Destape de cañerías"],
  "Distribuidora": ["Distributor", "Distribuidora"],
  "Distribuidora de bebidas": ["Beverage distributor", "Distribuidora de bebidas"],
  "E-commerce": ["E-commerce", "Comercio electrónico"],
  "Editora": ["Publishing house", "Editorial"],
  "Elétrica industrial": ["Industrial electrical", "Eléctrica industrial"],
  "Embalagens": ["Packaging", "Embalajes"],
  "Empreiteira": ["Contractor", "Empresa contratista"],
  "Empresa (café corporativo)": ["Company (office coffee)", "Empresa (café corporativo)"],
  "Empresa (café da manhã corporativo)": ["Company (corporate breakfast)", "Empresa (desayuno corporativo)"],
  "Empresa (comércio exterior)": ["Company (foreign trade)", "Empresa (comercio exterior)"],
  "Empresa (convênio corporativo)": ["Company (corporate benefits)", "Empresa (convenio corporativo)"],
  "Empresa (eventos corporativos)": ["Company (corporate events)", "Empresa (eventos corporativos)"],
  "Empresa (exames admissionais)": ["Company (pre-employment exams)", "Empresa (exámenes de ingreso)"],
  "Empresa (frota executiva)": ["Company (executive fleet)", "Empresa (flota ejecutiva)"],
  "Empresa (marketing/publicidade)": ["Company (marketing/advertising)", "Empresa (marketing/publicidad)"],
  "Empresa (parceria corporativa)": ["Company (corporate partnership)", "Empresa (alianza corporativa)"],
  "Empresa (parceria corporativa/wellness)": ["Company (corporate wellness partnership)", "Empresa (alianza corporativa/bienestar)"],
  "Empresa (saúde mental corporativa)": ["Company (corporate mental health)", "Empresa (salud mental corporativa)"],
  "Empresa (saúde ocupacional)": ["Company (occupational health)", "Empresa (salud ocupacional)"],
  "Empresa (treinamento corporativo)": ["Company (corporate training)", "Empresa (capacitación corporativa)"],
  "Empresa (turismo corporativo)": ["Company (corporate travel)", "Empresa (turismo corporativo)"],
  "Empresa (viagens corporativas)": ["Company (business travel)", "Empresa (viajes corporativos)"],
  "Empresa (wellness corporativo)": ["Company (corporate wellness)", "Empresa (bienestar corporativo)"],
  "Empresa em geral": ["Companies in general", "Empresas en general"],
  "Engenharia": ["Engineering", "Ingeniería"],
  "Engenharia civil": ["Civil engineering", "Ingeniería civil"],
  "Escola": ["School", "Escuela"],
  "Escola (parceria)": ["School (partnership)", "Escuela (alianza)"],
  "Escritório": ["Office", "Oficina"],
  "Escritório de advocacia": ["Law office", "Estudio jurídico"],
  "Escritório de marketing": ["Marketing office", "Oficina de marketing"],
  "Esquadrias": ["Window and door frames", "Carpintería metálica"],
  "Esquadrias de alumínio": ["Aluminium frames", "Carpintería de aluminio"],
  "Estacionamento": ["Parking facility", "Estacionamiento"],
  "Estaleiro naval": ["Shipyard", "Astillero"],
  "Estrutura metálica": ["Steel structures", "Estructura metálica"],
  "Evento": ["Event", "Evento"],
  "Evento corporativo": ["Corporate event", "Evento corporativo"],
  "Eventos": ["Events", "Eventos"],
  "Eventos e feiras": ["Events and trade shows", "Eventos y ferias"],
  "Exportadora": ["Exporter", "Exportadora"],
  "Fabricante de eletrodomésticos": ["Appliance manufacturer", "Fabricante de electrodomésticos"],
  "Fabricante de máquinas": ["Machinery manufacturer", "Fabricante de máquinas"],
  "Fabricante de móveis": ["Furniture manufacturer", "Fabricante de muebles"],
  "Família/Pessoa física": ["Household / individual", "Familia / persona física"],
  "Farmacêutica": ["Pharmaceutical company", "Farmacéutica"],
  "Farmácia": ["Pharmacy", "Farmacia"],
  "Fazenda": ["Farm", "Finca"],
  "Feira": ["Trade fair", "Feria"],
  "Feira e exposição": ["Trade fairs and expos", "Ferias y exposiciones"],
  "Fisioterapia": ["Physiotherapy", "Fisioterapia"],
  "Franquia": ["Franchise", "Franquicia"],
  "Frigorífico": ["Meat processing plant", "Frigorífico"],
  "Frota de veículos": ["Vehicle fleet", "Flota de vehículos"],
  "Frota empresarial": ["Corporate fleet", "Flota empresarial"],
  "Fundição": ["Foundry", "Fundición"],
  "Fábrica": ["Factory", "Fábrica"],
  "Haras": ["Horse breeding farm", "Haras"],
  "Home care": ["Home care", "Atención domiciliaria"],
  "Hospital": ["Hospital", "Hospital"],
  "Hotel": ["Hotel", "Hotel"],
  "Hotel para pets": ["Pet hotel", "Hotel para mascotas"],
  "Imobiliária": ["Real estate agency", "Inmobiliaria"],
  "Impermeabilização": ["Waterproofing", "Impermeabilización"],
  "Importadora": ["Importer", "Importadora"],
  "Incorporadora": ["Property developer", "Desarrolladora inmobiliaria"],
  "Indústria": ["Industry", "Industria"],
  "Indústria alimentícia": ["Food industry", "Industria alimentaria"],
  "Indústria automotiva": ["Automotive industry", "Industria automotriz"],
  "Indústria de alumínio": ["Aluminium industry", "Industria del aluminio"],
  "Indústria de embalagens": ["Packaging industry", "Industria del embalaje"],
  "Indústria metalúrgica": ["Metallurgical industry", "Industria metalúrgica"],
  "Indústria química": ["Chemical industry", "Industria química"],
  "Indústria têxtil": ["Textile industry", "Industria textil"],
  "Instalação de ar-condicionado": ["Air conditioning installation", "Instalación de aire acondicionado"],
  "Instituição de ensino": ["Educational institution", "Institución educativa"],
  "Investidor imobiliário": ["Real estate investor", "Inversor inmobiliario"],
  "Jateamento abrasivo": ["Abrasive blasting", "Arenado abrasivo"],
  "Laboratório": ["Laboratory", "Laboratorio"],
  "Lavanderia industrial": ["Industrial laundry", "Lavandería industrial"],
  "Limpeza de fachadas": ["Facade cleaning", "Limpieza de fachadas"],
  "Limpeza industrial": ["Industrial cleaning", "Limpieza industrial"],
  "Locadora de veículos": ["Car rental company", "Alquiler de autos"],
  "Locação de equipamentos": ["Equipment rental", "Alquiler de equipos"],
  "Logística": ["Logistics", "Logística"],
  "Logística e armazenagem": ["Logistics and warehousing", "Logística y almacenamiento"],
  "Loja": ["Store", "Tienda"],
  "Loja de conveniência": ["Convenience store", "Tienda de conveniencia"],
  "Loja de cosméticos": ["Cosmetics store", "Tienda de cosméticos"],
  "Loja de material de construção": ["Building supply store", "Tienda de materiales de construcción"],
  "Loteadora": ["Land subdivision developer", "Loteadora"],
  "Loteamento": ["Land development", "Loteo"],
  "Malharia": ["Knitwear manufacturer", "Tejeduría"],
  "Manutenção industrial": ["Industrial maintenance", "Mantenimiento industrial"],
  "Manutenção predial": ["Building maintenance", "Mantenimiento de edificios"],
  "Maquinário agrícola": ["Agricultural machinery", "Maquinaria agrícola"],
  "Marcenaria": ["Carpentry", "Carpintería"],
  "Marketplace": ["Marketplace", "Marketplace"],
  "Marmoraria": ["Stonemason", "Marmolería"],
  "Mecânica automotiva": ["Auto repair shop", "Taller mecánico"],
  "Mercado": ["Grocery store", "Mercado"],
  "Metrologia": ["Metrology", "Metrología"],
  "Mineração": ["Mining", "Minería"],
  "Montagem industrial": ["Industrial assembly", "Montaje industrial"],
  "Multinacional": ["Multinational company", "Multinacional"],
  "ONG de animais": ["Animal welfare NGO", "ONG de animales"],
  "Oficina mecânica": ["Auto repair shop", "Taller mecánico"],
  "Operadora de turismo": ["Tour operator", "Operadora turística"],
  "Padaria": ["Bakery", "Panadería"],
  "Paisagismo": ["Landscaping", "Paisajismo"],
  "Papel e celulose": ["Pulp and paper", "Papel y celulosa"],
  "Pet shop": ["Pet shop", "Pet shop"],
  "Petroquímica": ["Petrochemical", "Petroquímica"],
  "Pintura industrial": ["Industrial painting", "Pintura industrial"],
  "Pintura predial": ["Building painting", "Pintura de edificios"],
  "Plano de saúde": ["Health insurance provider", "Seguro de salud"],
  "Posto de combustível": ["Gas station", "Estación de servicio"],
  "Prefeitura": ["City government", "Municipalidad"],
  "Profissional autônomo": ["Self-employed professional", "Profesional autónomo"],
  "Proprietário de imóvel": ["Property owner", "Propietario de inmueble"],
  "Reflorestamento": ["Reforestation", "Reforestación"],
  "Reforma comercial": ["Commercial renovation", "Remodelación comercial"],
  "Reforma residencial": ["Home renovation", "Remodelación residencial"],
  "Representante comercial": ["Sales representative", "Representante comercial"],
  "Restaurante": ["Restaurant", "Restaurante"],
  "Salão de beleza": ["Beauty salon", "Salón de belleza"],
  "Saneamento": ["Sanitation utility", "Saneamiento"],
  "Secretaria de educação": ["Department of education", "Secretaría de educación"],
  "Seguradora": ["Insurance company", "Aseguradora"],
  "Segurança patrimonial": ["Property security", "Seguridad patrimonial"],
  "Serralheria": ["Metalwork shop", "Herrería"],
  "Shopping": ["Shopping mall", "Centro comercial"],
  "Shopping center": ["Shopping mall", "Centro comercial"],
  "Sindicato": ["Trade union", "Sindicato"],
  "Solda industrial": ["Industrial welding", "Soldadura industrial"],
  "Spa": ["Spa", "Spa"],
  "Startup": ["Startup", "Startup"],
  "Startup de produto": ["Product startup", "Startup de producto"],
  "Supermercado": ["Supermarket", "Supermercado"],
  "Telecomunicações": ["Telecommunications", "Telecomunicaciones"],
  "Terraplanagem": ["Earthworks", "Movimiento de suelos"],
  "Transportadora": ["Trucking company", "Transportista"],
  "Transporte de cargas": ["Freight transport", "Transporte de cargas"],
  "Universidade": ["University", "Universidad"],
  "Usina": ["Plant", "Planta industrial"],
  "Usina de cana": ["Sugarcane mill", "Ingenio azucarero"],
  "Usinagem": ["Machining", "Mecanizado"],
  "Varejo": ["Retail", "Comercio minorista"],
  "Vinícola": ["Winery", "Bodega"],
  "abertura e regularização de empresas": ["business registration services", "constitución y regularización de empresas"],
  "abrasivos e ferramentas de corte": ["abrasives and cutting tools", "abrasivos y herramientas de corte"],
  "academia": ["gym", "gimnasio"],
  "adesivagem de frota": ["fleet vehicle wrapping", "rotulación de flota"],
  "administração de condomínios": ["property management", "administración de condominios"],
  "administração de imóveis": ["real estate management", "administración de inmuebles"],
  "advocacia": ["legal services", "servicios jurídicos"],
  "agenciamento de cargas": ["freight forwarding", "agenciamiento de cargas"],
  "agência de viagens": ["travel agency", "agencia de viajes"],
  "alarme e monitoramento": ["alarm and monitoring", "alarma y monitoreo"],
  "aluguel de betoneiras": ["concrete mixer rental", "alquiler de hormigoneras"],
  "aluguel de caminhões": ["truck rental", "alquiler de camiones"],
  "aluguel de containers": ["container rental", "alquiler de contenedores"],
  "andaimes e acesso": ["scaffolding and access", "andamios y acceso"],
  "anodização": ["anodising", "anodizado"],
  "análise de solo": ["soil analysis", "análisis de suelo"],
  "armazém geral": ["general warehousing", "almacén general"],
  "arquivo e guarda de documentos": ["document storage", "archivo y custodia de documentos"],
  "assessoria de imprensa": ["press relations", "prensa y comunicación"],
  "assessoria em importação": ["import advisory", "asesoría en importación"],
  "assessoria trabalhista": ["labour law advisory", "asesoría laboral"],
  "assinatura digital e certificado": ["digital signature and certificates", "firma digital y certificados"],
  "atacadista": ["wholesaler", "mayorista"],
  "auditoria e compliance": ["audit and compliance", "auditoría y compliance"],
  "auto elétrica": ["auto electrical repair", "electricidad automotriz"],
  "automação comercial e pdv": ["retail automation and POS", "automatización comercial y punto de venta"],
  "automação industrial": ["industrial automation", "automatización industrial"],
  "automação residencial": ["home automation", "automatización residencial"],
  "avaliação de imóveis": ["property appraisal", "tasación de inmuebles"],
  "backup e nuvem": ["backup and cloud", "respaldo y nube"],
  "banheiro químico": ["portable toilets", "baños químicos"],
  "barbearia": ["barbershop", "barbería"],
  "blindagem de veículos": ["vehicle armouring", "blindaje de vehículos"],
  "bombas industriais": ["industrial pumps", "bombas industriales"],
  "bordado e estamparia": ["embroidery and screen printing", "bordado y estampado"],
  "borracha e vedação": ["rubber and sealing", "caucho y sellado"],
  "borracharia e pneus": ["tyre shop", "gomería y neumáticos"],
  "brigada de incêndio": ["fire brigade training", "brigada de incendios"],
  "brindes corporativos": ["corporate gifts", "regalos corporativos"],
  "buffet de eventos": ["event catering", "catering para eventos"],
  "cabeamento estruturado": ["structured cabling", "cableado estructurado"],
  "caldeiraria": ["boilermaking", "calderería"],
  "caldeiras e vasos de pressão": ["boilers and pressure vessels", "calderas y recipientes a presión"],
  "calibração de instrumentos": ["instrument calibration", "calibración de instrumentos"],
  "catering corporativo": ["corporate catering", "catering corporativo"],
  "cerca elétrica e concertina": ["electric fencing and razor wire", "cerco eléctrico y concertina"],
  "cercas e currais": ["fencing and corrals", "cercos y corrales"],
  "certificação iso": ["ISO certification", "certificación ISO"],
  "climatização industrial": ["industrial HVAC", "climatización industrial"],
  "clínica de estética": ["aesthetic clinic", "clínica estética"],
  "clínica médica": ["medical clinic", "clínica médica"],
  "clínica odontológica": ["dental clinic", "clínica dental"],
  "clínica veterinária": ["veterinary clinic", "clínica veterinaria"],
  "cobrança e recuperação de crédito": ["debt collection", "cobranza y recuperación de crédito"],
  "colheita mecanizada": ["mechanised harvesting", "cosecha mecanizada"],
  "combustível e arla para frotas": ["fleet fuel supply", "combustible para flotas"],
  "compressores de ar": ["air compressors", "compresores de aire"],
  "comunicação visual e fachadas": ["signage and storefronts", "comunicación visual y fachadas"],
  "concreto usinado": ["ready-mix concrete", "hormigón elaborado"],
  "confecção de uniformes": ["uniform manufacturing", "confección de uniformes"],
  "conservação e zeladoria": ["facility upkeep", "conservación y mantenimiento"],
  "construção civil": ["civil construction", "construcción civil"],
  "consultoria agronômica": ["agronomic consulting", "consultoría agronómica"],
  "consultoria ambiental": ["environmental consulting", "consultoría ambiental"],
  "consultoria de crédito empresarial": ["business credit advisory", "consultoría de crédito empresarial"],
  "consultoria de marketing": ["marketing consulting", "consultoría de marketing"],
  "consultoria educacional": ["education consulting", "consultoría educativa"],
  "consultoria em lgpd": ["data protection consulting", "consultoría en protección de datos"],
  "consultoria em processos": ["process consulting", "consultoría en procesos"],
  "consultoria em segurança alimentar": ["food safety consulting", "consultoría en seguridad alimentaria"],
  "consultoria em ti": ["IT consulting", "consultoría en TI"],
  "consultoria financeira": ["financial consulting", "consultoría financiera"],
  "consultoria pedagógica": ["pedagogical consulting", "consultoría pedagógica"],
  "consultoria tributária": ["tax consulting", "consultoría tributaria"],
  "consumíveis de solda": ["welding consumables", "consumibles de soldadura"],
  "contabilidade": ["accounting", "contabilidad"],
  "contabilidade digital": ["online accounting", "contabilidad digital"],
  "controle de acesso e portaria": ["access control and reception", "control de acceso y portería"],
  "correias transportadoras": ["conveyor belts", "cintas transportadoras"],
  "corretagem comercial": ["commercial brokerage", "corretaje comercial"],
  "corretora de investimentos": ["investment brokerage", "corredora de inversiones"],
  "corretora de seguros": ["insurance brokerage", "corredora de seguros"],
  "corte a laser": ["laser cutting", "corte láser"],
  "corte e dobra de chapas": ["sheet metal cutting and bending", "corte y plegado de chapas"],
  "coworking e escritório virtual": ["coworking and virtual office", "coworking y oficina virtual"],
  "criação de site e landing page": ["website and landing page design", "creación de sitios y landing pages"],
  "curso de idiomas": ["language courses", "cursos de idiomas"],
  "cursos técnicos": ["technical courses", "cursos técnicos"],
  "câmara fria": ["cold storage rooms", "cámara frigorífica"],
  "decoração de eventos": ["event decoration", "decoración de eventos"],
  "dedetização e controle de pragas": ["pest control", "fumigación y control de plagas"],
  "demolição": ["demolition", "demolición"],
  "descarte de resíduos hospitalares": ["medical waste disposal", "descarte de residuos hospitalarios"],
  "desentupimento": ["drain unclogging", "destape de cañerías"],
  "desenvolvimento de software": ["software development", "desarrollo de software"],
  "design gráfico": ["graphic design", "diseño gráfico"],
  "despachante aduaneiro": ["customs broker", "despachante de aduana"],
  "digitalização de documentos": ["document digitisation", "digitalización de documentos"],
  "distribuidor de autopeças": ["auto parts distributor", "distribuidor de autopartes"],
  "distribuidor de cosméticos": ["cosmetics distributor", "distribuidor de cosméticos"],
  "distribuidor de rochas ornamentais": ["dimension stone distributor", "distribuidor de piedras ornamentales"],
  "distribuidora de abrasivos": ["abrasives distributor", "distribuidora de abrasivos"],
  "distribuidora de alimentos": ["food distributor", "distribuidora de alimentos"],
  "distribuidora de aço e metais": ["steel and metals distributor", "distribuidora de acero y metales"],
  "distribuidora de bebidas": ["beverage distributor", "distribuidora de bebidas"],
  "distribuidora de embalagens": ["packaging distributor", "distribuidora de embalajes"],
  "distribuidora de epi": ["PPE distributor", "distribuidora de EPP"],
  "distribuidora de material elétrico": ["electrical supplies distributor", "distribuidora de material eléctrico"],
  "distribuidora de material hidráulico": ["plumbing supplies distributor", "distribuidora de material sanitario"],
  "distribuidora de tintas industriais": ["industrial paint distributor", "distribuidora de pinturas industriales"],
  "drenagem e saneamento": ["drainage and sanitation", "drenaje y saneamiento"],
  "e-commerce e marketplace": ["e-commerce and marketplace", "comercio electrónico y marketplace"],
  "elétrica industrial": ["industrial electrical", "eléctrica industrial"],
  "energia no mercado livre": ["deregulated energy supply", "energía en mercado libre"],
  "energia solar": ["solar energy", "energía solar"],
  "ensaios não destrutivos (ndt)": ["non-destructive testing (NDT)", "ensayos no destructivos (END)"],
  "epi e segurança do trabalho": ["PPE and workplace safety", "EPP y seguridad laboral"],
  "equipamentos de fisioterapia": ["physiotherapy equipment", "equipos de fisioterapia"],
  "erp e sistemas de gestão": ["ERP and management systems", "ERP y sistemas de gestión"],
  "escavação e movimentação de terra": ["excavation and earthmoving", "excavación y movimiento de suelos"],
  "escola de idiomas corporativa": ["corporate language school", "escuela de idiomas corporativa"],
  "esquadrias de alumínio": ["aluminium frames", "carpintería de aluminio"],
  "esterilização de materiais": ["sterilisation services", "esterilización de materiales"],
  "estrutura metálica": ["steel structures", "estructura metálica"],
  "exames ocupacionais": ["occupational health exams", "exámenes ocupacionales"],
  "extintores e combate a incêndio": ["fire extinguishers and firefighting", "extintores y combate de incendios"],
  "fabricação de embalagens": ["packaging manufacturing", "fabricación de embalajes"],
  "factoring": ["factoring", "factoring"],
  "fisioterapia": ["physiotherapy", "fisioterapia"],
  "food truck": ["food truck", "food truck"],
  "fornecedor de andaimes e escoras": ["scaffolding and shoring supplier", "proveedor de andamios y puntales"],
  "fornecedor de equipamentos hospitalares": ["hospital equipment supplier", "proveedor de equipos hospitalarios"],
  "fornecedor de equipamentos para restaurantes": ["restaurant equipment supplier", "proveedor de equipos para restaurantes"],
  "fornecedor de hortifruti": ["produce supplier", "proveedor de frutas y verduras"],
  "fornecedor de máquinas para marmoraria": ["stoneworking machinery supplier", "proveedor de máquinas para marmolería"],
  "forro de pvc e modular": ["PVC and modular ceilings", "cielorraso de PVC y modular"],
  "fotografia e filmagem": ["photography and video", "fotografía y filmación"],
  "frete e mudanças": ["freight and moving", "fletes y mudanzas"],
  "frigorífico e distribuição de carnes": ["meat processing and distribution", "frigorífico y distribución de carnes"],
  "fulfillment e-commerce": ["e-commerce fulfilment", "fulfillment para e-commerce"],
  "fundações e estacas": ["foundations and piling", "fundaciones y pilotes"],
  "fundição": ["foundry", "fundición"],
  "funilaria e pintura automotiva": ["auto body and paint", "chapa y pintura automotriz"],
  "fôrmas e escoramentos": ["formwork and shoring", "encofrados y apuntalamiento"],
  "galvanização e zincagem": ["galvanising and zinc plating", "galvanizado y zincado"],
  "gases medicinais": ["medical gases", "gases medicinales"],
  "gesso e drywall": ["plaster and drywall", "yeso y durlock"],
  "gestão de redes sociais": ["social media management", "gestión de redes sociales"],
  "gestão de resíduos": ["waste management", "gestión de residuos"],
  "gráfica": ["print shop", "imprenta"],
  "guincho e reboque": ["towing service", "grúa y remolque"],
  "higienização de veículos": ["vehicle detailing", "higienización de vehículos"],
  "home care": ["home care", "atención domiciliaria"],
  "home staging e decoração para venda": ["home staging", "home staging y decoración para venta"],
  "hotel": ["hotel", "hotel"],
  "iluminação e luminotécnica": ["lighting design", "iluminación y luminotecnia"],
  "imobiliária": ["real estate agency", "inmobiliaria"],
  "impermeabilização": ["waterproofing", "impermeabilización"],
  "impermeabilização de lajes": ["roof slab waterproofing", "impermeabilización de losas"],
  "impressão 3d": ["3D printing", "impresión 3D"],
  "infraestrutura de rede": ["network infrastructure", "infraestructura de red"],
  "injeção plástica": ["plastic injection moulding", "inyección de plásticos"],
  "instalação de ar-condicionado": ["air conditioning installation", "instalación de aire acondicionado"],
  "instalação de câmeras e cftv": ["CCTV installation", "instalación de cámaras y CCTV"],
  "instrumentação industrial": ["industrial instrumentation", "instrumentación industrial"],
  "insulfilm e película de segurança": ["window tinting and security film", "polarizado y película de seguridad"],
  "irrigação agrícola": ["agricultural irrigation", "riego agrícola"],
  "isolamento térmico industrial": ["industrial thermal insulation", "aislamiento térmico industrial"],
  "jardinagem e paisagismo": ["gardening and landscaping", "jardinería y paisajismo"],
  "jateamento abrasivo": ["abrasive blasting", "arenado abrasivo"],
  "laboratório de análises clínicas": ["clinical laboratory", "laboratorio de análisis clínicos"],
  "laudo técnico e avcb": ["technical reports and fire safety certificates", "informes técnicos y certificados de bomberos"],
  "lavanderia industrial": ["industrial laundry", "lavandería industrial"],
  "limpeza de caixa d'água": ["water tank cleaning", "limpieza de tanques de agua"],
  "limpeza de fachadas": ["facade cleaning", "limpieza de fachadas"],
  "limpeza industrial": ["industrial cleaning", "limpieza industrial"],
  "limpeza pós-obra": ["post-construction cleaning", "limpieza post obra"],
  "locação de empilhadeiras": ["forklift rental", "alquiler de autoelevadores"],
  "locação de equipamentos": ["equipment rental", "alquiler de equipos"],
  "locação de equipamentos de ti": ["IT equipment rental", "alquiler de equipos de TI"],
  "locação de geradores": ["generator rental", "alquiler de generadores"],
  "locação de guindastes": ["crane rental", "alquiler de grúas"],
  "locação de impressoras": ["printer rental", "alquiler de impresoras"],
  "locação de mobiliário para eventos": ["event furniture rental", "alquiler de mobiliario para eventos"],
  "locação de plataformas elevatórias": ["aerial lift rental", "alquiler de plataformas elevadoras"],
  "locação de tendas e estruturas": ["tent and structure rental", "alquiler de carpas y estructuras"],
  "logística e armazenagem": ["logistics and warehousing", "logística y almacenamiento"],
  "loja de informática": ["computer store", "tienda de informática"],
  "loja de material de construção": ["building supply store", "tienda de materiales de construcción"],
  "lubrificação industrial": ["industrial lubrication", "lubricación industrial"],
  "mangueiras industriais": ["industrial hoses", "mangueras industriales"],
  "manutenção de ar-condicionado": ["air conditioning maintenance", "mantenimiento de aire acondicionado"],
  "manutenção de computadores": ["computer repair", "mantenimiento de computadoras"],
  "manutenção de elevadores": ["lift maintenance", "mantenimiento de ascensores"],
  "manutenção de empilhadeiras": ["forklift maintenance", "mantenimiento de autoelevadores"],
  "manutenção de equipamentos de cozinha": ["kitchen equipment maintenance", "mantenimiento de equipos de cocina"],
  "manutenção de equipamentos médicos": ["medical equipment maintenance", "mantenimiento de equipos médicos"],
  "manutenção de geradores": ["generator maintenance", "mantenimiento de generadores"],
  "manutenção de motores elétricos": ["electric motor maintenance", "mantenimiento de motores eléctricos"],
  "manutenção de máquinas agrícolas": ["farm machinery maintenance", "mantenimiento de maquinaria agrícola"],
  "manutenção mecânica industrial": ["industrial mechanical maintenance", "mantenimiento mecánico industrial"],
  "manutenção predial": ["building maintenance", "mantenimiento de edificios"],
  "manutenção preditiva": ["predictive maintenance", "mantenimiento predictivo"],
  "maquininha de cartão e meios de pagamento": ["card readers and payment processing", "terminales de pago y medios de cobro"],
  "maquinário agrícola": ["agricultural machinery", "maquinaria agrícola"],
  "marcenaria sob medida": ["custom carpentry", "carpintería a medida"],
  "marketing digital": ["digital marketing", "marketing digital"],
  "marmoraria": ["stonemason", "marmolería"],
  "material didático": ["educational materials", "material didáctico"],
  "mecânica automotiva": ["auto repair", "mecánica automotriz"],
  "medicamentos veterinários": ["veterinary medicines", "medicamentos veterinarios"],
  "medicina do trabalho": ["occupational medicine", "medicina laboral"],
  "montagem de estandes": ["trade show booth construction", "montaje de stands"],
  "montagem industrial": ["industrial assembly", "montaje industrial"],
  "móveis planejados": ["custom furniture", "muebles a medida"],
  "nobreak e energia de emergência": ["UPS and backup power", "UPS y energía de emergencia"],
  "nutrição": ["nutrition services", "nutrición"],
  "nutrição animal": ["animal nutrition", "nutrición animal"],
  "outsourcing de impressão": ["managed print services", "outsourcing de impresión"],
  "padaria e confeitaria": ["bakery and pastry", "panadería y pastelería"],
  "paletes e embalagem para transporte": ["pallets and transport packaging", "pallets y embalaje para transporte"],
  "papel de parede e adesivagem": ["wallpaper and wall decals", "papel tapiz y vinilos"],
  "papelaria": ["stationery supplies", "papelería"],
  "para-raios e spda": ["lightning protection systems", "pararrayos y protección contra rayos"],
  "pavimentação asfáltica": ["asphalt paving", "pavimentación asfáltica"],
  "persianas e cortinas": ["blinds and curtains", "persianas y cortinas"],
  "personal trainer": ["personal trainer", "entrenador personal"],
  "perícia contábil": ["forensic accounting", "peritaje contable"],
  "pesquisa de mercado": ["market research", "investigación de mercado"],
  "pet shop": ["pet shop", "pet shop"],
  "peças para máquinas pesadas": ["heavy machinery parts", "repuestos para maquinaria pesada"],
  "pintura eletrostática": ["powder coating", "pintura electrostática"],
  "pintura industrial": ["industrial painting", "pintura industrial"],
  "pintura predial": ["building painting", "pintura de edificios"],
  "piso industrial e epóxi": ["industrial and epoxy flooring", "piso industrial y epóxico"],
  "piso vinílico e laminado": ["vinyl and laminate flooring", "piso vinílico y laminado"],
  "plano de saúde empresarial": ["corporate health plans", "seguro de salud empresarial"],
  "poda de árvores": ["tree pruning", "poda de árboles"],
  "porcelanato e revestimento": ["porcelain tile and cladding", "porcelanato y revestimientos"],
  "portaria e recepção terceirizada": ["outsourced reception and front desk", "portería y recepción tercerizada"],
  "portaria remota": ["remote gatekeeping", "portería remota"],
  "produtos químicos para limpeza": ["cleaning chemicals", "productos químicos de limpieza"],
  "produção de vídeo institucional": ["corporate video production", "producción de video institucional"],
  "provedor de internet": ["internet service provider", "proveedor de internet"],
  "pré-moldados de concreto": ["precast concrete", "prefabricados de hormigón"],
  "prótese dentária": ["dental prosthetics", "prótesis dental"],
  "psicologia clínica": ["clinical psychology", "psicología clínica"],
  "pulverização agrícola com drone": ["drone crop spraying", "pulverización agrícola con drones"],
  "rastreamento veicular": ["vehicle tracking", "rastreo vehicular"],
  "recursos humanos / recrutamento": ["HR and recruitment", "recursos humanos / reclutamiento"],
  "redes de proteção": ["safety netting", "redes de protección"],
  "refratários": ["refractories", "refractarios"],
  "refrigeração comercial": ["commercial refrigeration", "refrigeración comercial"],
  "regularização de imóveis": ["property title regularisation", "regularización de inmuebles"],
  "restaurante": ["restaurant", "restaurante"],
  "retífica de motores": ["engine rebuilding", "rectificación de motores"],
  "rolamentos e transmissão": ["bearings and power transmission", "rodamientos y transmisión"],
  "rotulagem e etiquetas": ["labelling and tags", "etiquetado y etiquetas"],
  "salão de beleza": ["beauty salon", "salón de belleza"],
  "segurança da informação": ["information security", "seguridad de la información"],
  "segurança para eventos": ["event security", "seguridad para eventos"],
  "segurança patrimonial": ["property security", "seguridad patrimonial"],
  "seguro de frota": ["fleet insurance", "seguro de flota"],
  "seguro empresarial": ["business insurance", "seguro empresarial"],
  "sementes e mudas": ["seeds and seedlings", "semillas y plantines"],
  "serralheria": ["metalwork", "herrería"],
  "silos e armazenagem de grãos": ["silos and grain storage", "silos y almacenamiento de granos"],
  "sinalização e placas": ["signage and signs", "señalización y carteles"],
  "sinalização industrial": ["industrial signage", "señalización industrial"],
  "software de gestão de obras": ["construction management software", "software de gestión de obras"],
  "software para clínicas": ["clinic management software", "software para clínicas"],
  "software para escritórios": ["office management software", "software para oficinas"],
  "software para transportadoras": ["trucking management software", "software para transportistas"],
  "solda industrial": ["industrial welding", "soldadura industrial"],
  "som e iluminação para eventos": ["event sound and lighting", "sonido e iluminación para eventos"],
  "sondagem de solo": ["soil boring", "sondeo de suelo"],
  "sopro de plásticos": ["plastic blow moulding", "soplado de plásticos"],
  "sprinklers e hidrantes": ["sprinklers and hydrants", "rociadores e hidrantes"],
  "suporte técnico de ti": ["IT support", "soporte técnico de TI"],
  "telecomunicações": ["telecommunications", "telecomunicaciones"],
  "telefonia empresarial": ["business telephony", "telefonía empresarial"],
  "telefonia voip e pabx": ["VoIP and PBX telephony", "telefonía VoIP y PBX"],
  "telhado e cobertura metálica": ["metal roofing", "techos y cubiertas metálicas"],
  "terceirização de mão de obra": ["labour outsourcing", "tercerización de mano de obra"],
  "termoformagem": ["thermoforming", "termoformado"],
  "terraplanagem": ["earthworks", "movimiento de suelos"],
  "textura e grafiato": ["textured wall finishes", "texturas y revoques decorativos"],
  "tinturaria e acabamento têxtil": ["textile dyeing and finishing", "tintorería y acabado textil"],
  "torrefação de café": ["coffee roasting", "tostado de café"],
  "tradução e interpretação": ["translation and interpreting", "traducción e interpretación"],
  "transportadora": ["trucking company", "transportista"],
  "transporte de cargas": ["freight transport", "transporte de cargas"],
  "transporte de cargas perigosas": ["hazardous goods transport", "transporte de cargas peligrosas"],
  "transporte refrigerado": ["refrigerated transport", "transporte refrigerado"],
  "tratamento de superfícies": ["surface treatment", "tratamiento de superficies"],
  "tratamento de água e efluentes": ["water and wastewater treatment", "tratamiento de agua y efluentes"],
  "tratamento térmico de metais": ["metal heat treatment", "tratamiento térmico de metales"],
  "treinamento corporativo": ["corporate training", "capacitación corporativa"],
  "treinamento nr (segurança)": ["workplace safety training", "capacitación en seguridad laboral"],
  "tráfego pago": ["paid media", "tráfico pago"],
  "tubulação industrial": ["industrial piping", "tuberías industriales"],
  "uniformes profissionais": ["work uniforms", "uniformes profesionales"],
  "usinagem cnc": ["CNC machining", "mecanizado CNC"],
  "vale-refeição e benefícios": ["meal vouchers and benefits", "vales de comida y beneficios"],
  "vasos de pressão": ["pressure vessels", "recipientes a presión"],
  "venda de insumos agrícolas": ["agricultural input supply", "venta de insumos agrícolas"],
  "veterinária de grande porte": ["large animal veterinary", "veterinaria de grandes animales"],
  "vidraçaria": ["glazier", "vidriería"],
  "vidro temperado e box": ["tempered glass and shower enclosures", "vidrio templado y mamparas"],
  "vigilância eletrônica": ["electronic surveillance", "vigilancia electrónica"],
  "vistoria de imóveis": ["property inspection", "inspección de inmuebles"],
  "Ônibus": ["Bus operator", "Empresa de autobuses"],
  "óptica e lentes": ["optics and lenses", "óptica y lentes"],}

/** Remove acento e caixa para a busca tolerar variação de digitação */
function normalizar(texto: string): string {
  return texto
    .toLowerCase()
    .trim()
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
}

/**
 * Índice reverso, montado uma vez: qualquer idioma → termo canônico PT.
 *
 * Construído na primeira consulta, e não no carregamento do módulo,
 * para não custar nada a quem nunca troca de idioma.
 */
let indiceReverso: Map<string, string> | null = null

function obterIndiceReverso(): Map<string, string> {
  if (indiceReverso) return indiceReverso

  const indice = new Map<string, string>()
  for (const [pt, [en, es]] of Object.entries(TRADUCAO_SEGMENTOS)) {
    indice.set(normalizar(pt), pt)
    // Quando dois termos em português compartilham a mesma tradução
    // (ex.: "Mecânica automotiva" e "Oficina mecânica"), o primeiro
    // vence. Como o mapa casa por substring, qualquer um dos dois
    // chega no mesmo conjunto de ramos-cliente.
    if (!indice.has(normalizar(en))) indice.set(normalizar(en), pt)
    if (!indice.has(normalizar(es))) indice.set(normalizar(es), pt)
  }
  indiceReverso = indice
  return indice
}

/**
 * Converte um ramo digitado em qualquer idioma para o termo canônico
 * em português. Devolve a entrada intacta quando não reconhece — o
 * texto livre continua funcionando, só não ganha a tradução.
 */
export function canonizarSegmento(termo: string): string {
  if (!termo) return termo
  const encontrado = obterIndiceReverso().get(normalizar(termo))
  if (encontrado) return encontrado

  // Tenta por contenção: "dental clinic in Austin" ainda deve casar
  // com "Clínica odontológica".
  const alvo = normalizar(termo)
  for (const [chave, pt] of obterIndiceReverso()) {
    if (chave.length >= 5 && alvo.includes(chave)) return pt
  }
  return termo
}

/**
 * Traduz um termo canônico em português para o idioma informado.
 * Sem tradução cadastrada, devolve o próprio termo — melhor mostrar
 * português do que mostrar uma chave crua.
 */
export function traduzirSegmento(termoPt: string, idioma: string): string {
  const base = (idioma || "pt").split("-")[0]
  if (base === "pt") return termoPt

  const traducao = TRADUCAO_SEGMENTOS[termoPt]
  if (!traducao) return termoPt
  return base === "es" ? traducao[1] : traducao[0]
}
